### PR TITLE
Webkit2 port

### PR DESCRIPTION
**Pull request by cemeiq**
Port to Webkit2,changed signal name in infoview.py & replaced the deprecated methods of Webkit API with new methods of Webkit2 API

### CODE REVIEW

**Comment by cemeiq** [comment]
@chimosky Kindly review.

**Comment by Saumya-Mishra9129** [comment]
As this pr seems very old, I am thinking to work on this now.

**Comment by JuiP** [comment]
Does merging #3 close this PR? @Saumya-Mishra9129

**Comment by chimosky** [comment]
@JuiP no it doesn't, thanks for pointing it out.

**Pull request closed without merging**
